#ifndef _CHESSGTK_H
#define _CHESSGTK_H


#define MAX_MSGLEN  100 
#define SQUARE_SIZE 75  
#define WINDOW_BORDER 5
#define BOARD_BORDER 5
#define BOARD_WIDTH  (8*SQUARE_SIZE)
#define BOARD_HEIGHT (8*SQUARE_SIZE)
#define WINDOW_WIDTH  (BOARD_WIDTH + 2*BOARD_BORDER)
#define WINDOW_HEIGHT (BOARD_HEIGHT + 2*BOARD_BORDER)


#endif

